#ifndef MANZO_CORE_H
#define MANZO_CORE_H

/* Auto-generated by cbindgen — do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle returned by manzo_open and passed to all subsequent calls.
 * The real state lives behind a raw pointer cast to Arc<Mutex<InnerState>>.
 */
typedef struct manzo_ManzoHandle {
    uint8_t _private[0];
} manzo_ManzoHandle;

/**
 * Opens a file path for playback. Returns a non-null opaque handle on success,
 * or null on failure. Caller owns the handle; must call manzo_close to free.
 */
struct manzo_ManzoHandle *manzo_open(const char *path);

/**
 * Closes and frees the handle returned by manzo_open.
 */
void manzo_close(struct manzo_ManzoHandle *handle);

/**
 * Starts or resumes playback. Returns 0 on success, non-zero on error.
 */
int32_t manzo_play(struct manzo_ManzoHandle *handle);

/**
 * Pauses playback without resetting position.
 */
void manzo_pause(struct manzo_ManzoHandle *handle);

/**
 * Stops playback and resets position to start.
 */
void manzo_stop(struct manzo_ManzoHandle *handle);

/**
 * Seeks to `position_ms` milliseconds from start. Returns 0 on success.
 */
int32_t manzo_seek(struct manzo_ManzoHandle *handle, uint64_t position_ms);

/**
 * Sets the 10-band EQ gains. `gains` must point to an array of exactly 10 f32 values
 * in dB (range ±12.0). `preamp` is additional preamp gain in dB.
 */
void manzo_set_eq(struct manzo_ManzoHandle *handle, const float *gains, float preamp);

/**
 * Sets master volume. `volume` is in range [0.0, 1.0].
 */
void manzo_set_volume(struct manzo_ManzoHandle *handle, float volume);

/**
 * Sets stereo pan. `pan` is in range [-1.0, 1.0]; 0.0 = center.
 */
void manzo_set_pan(struct manzo_ManzoHandle *handle, float pan);

/**
 * Returns the current playback position in milliseconds.
 */
uint64_t manzo_get_position(struct manzo_ManzoHandle *handle);

/**
 * Fills `out_buf` with `count` float32 FFT magnitude values (range [0.0, 1.0]).
 * Returns number of values written. `out_buf` must be at least `count` elements.
 */
uintptr_t manzo_get_spectrum(struct manzo_ManzoHandle *handle, float *out_buf, uintptr_t count);

#endif  /* MANZO_CORE_H */
