import AppKit

@objc class AppDelegate: NSObject, NSApplicationDelegate {
    // MARK: - State

    // Keep handle alive for the app's lifetime — stored as instance var prevents premature dealloc.
    // Type matches cbindgen output: struct manzo_ManzoHandle * → UnsafeMutablePointer<manzo_ManzoHandle>?
    private var manzoHandle: UnsafeMutablePointer<manzo_ManzoHandle>? = nil

    // Phase 3 (D-02): playback state constants — must match the i32 returned by manzo_get_state.
    // Defined here as Int32 locals (rather than C macros in the bridging header) to keep this
    // task self-contained; cbindgen emits the function but not symbolic state names.
    private let MANZO_STATE_PLAYING: Int32 = 1
    private let MANZO_STATE_PAUSED:  Int32 = 2
    private let MANZO_STATE_STOPPED: Int32 = 3
    private let MANZO_STATE_ENDED:   Int32 = 4

    // Phase 3 (D-05 / AUDIO-05): 2-track queue and polling timer for auto-advance demo.
    // The Swift main thread polls manzo_get_state every 100 ms; when ENDED is observed the
    // current handle is closed and the next track is opened + played. A silence gap during
    // the handoff is acceptable per D-05 (true gapless deferred to v2).
    private var trackQueue: [String] = []
    private var currentTrackIndex: Int = 0
    private var pollTimer: Timer? = nil

    // MARK: - NSApplicationDelegate

    func applicationDidFinishLaunching(_ notification: Notification) {
        // Phase 3: build the 2-track queue. Each entry resolves the path the same way Phase 2
        // resolved test.mp3 — bundle resource first, then dev fixture fallback. test2.mp3 is
        // generated by Plan 03-02; if absent, the queue still holds test.mp3 and the
        // auto-advance log will show "queue exhausted" cleanly.
        trackQueue = [
            resolveFixturePath(name: "test",  ext: "mp3"),
            resolveFixturePath(name: "test2", ext: "mp3"),
        ]

        // Open + play the first track.
        let firstPath = trackQueue[currentTrackIndex]
        guard FileManager.default.fileExists(atPath: firstPath) else {
            NSLog("MANZO Phase 3: first track not found at \(firstPath) — skipping playback")
            return
        }
        manzoHandle = manzo_open(firstPath)
        guard let handle = manzoHandle else {
            NSLog("MANZO Phase 3: manzo_open returned null for \(firstPath)")
            return
        }
        let playResult = manzo_play(handle)
        if playResult == 0 {
            NSLog("MANZO Phase 3: playback started — \(firstPath)")
        } else {
            NSLog("MANZO Phase 3: manzo_play failed with code \(playResult) — \(firstPath)")
            return
        }

        // Phase 3 (D-05 / AUDIO-05): start 100 ms polling timer to detect ENDED and auto-advance.
        // Timer runs on the main runloop in default mode; pollPlaybackState reads state via FFI
        // and triggers the queue handoff when MANZO_STATE_ENDED is observed.
        pollTimer = Timer.scheduledTimer(
            timeInterval: 0.1,
            target: self,
            selector: #selector(pollPlaybackState),
            userInfo: nil,
            repeats: true
        )
        NSLog("MANZO Phase 3: 100 ms state poll timer armed — queue size \(trackQueue.count)")

        installUATKeyHandlers()  // Phase 4 UAT — remove after confirmed
    }

    func applicationWillTerminate(_ notification: Notification) {
        removeUATKeyHandlers()  // Phase 4 UAT — remove after confirmed

        // Phase 3: stop the poll timer FIRST so it cannot fire after the handle is freed.
        pollTimer?.invalidate()
        pollTimer = nil

        // Release Rust handle on app exit — manzo_close drops the Arc and stops cpal stream (T-02-09).
        if let handle = manzoHandle {
            manzo_close(handle)
            manzoHandle = nil
        }
    }

    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        return true
    }

    // MARK: - Phase 3: auto-advance polling

    /// Polls the Rust core's playback state. When MANZO_STATE_ENDED is observed, advance to
    /// the next track in trackQueue (close current handle, open + play next). When the queue
    /// is exhausted, invalidate the timer cleanly.
    @objc private func pollPlaybackState() {
        guard let handle = manzoHandle else { return }

        let state = manzo_get_state(handle)
        guard state == MANZO_STATE_ENDED else { return }

        NSLog("MANZO Phase 3: track ended (state=4) — advancing queue")

        // Close the current handle BEFORE opening the next one to avoid two cpal streams alive
        // simultaneously (cpal default device only supports one output stream at a time on macOS).
        manzo_close(handle)
        manzoHandle = nil

        // Advance the queue cursor.
        currentTrackIndex += 1
        guard currentTrackIndex < trackQueue.count else {
            NSLog("MANZO Phase 3: queue exhausted (\(currentTrackIndex)/\(trackQueue.count)) — stopping poll timer")
            pollTimer?.invalidate()
            pollTimer = nil
            return
        }

        let nextPath = trackQueue[currentTrackIndex]
        guard FileManager.default.fileExists(atPath: nextPath) else {
            NSLog("MANZO Phase 3: next track not found at \(nextPath) — stopping poll timer")
            pollTimer?.invalidate()
            pollTimer = nil
            return
        }

        manzoHandle = manzo_open(nextPath)
        guard let nextHandle = manzoHandle else {
            NSLog("MANZO Phase 3: manzo_open returned null for next track \(nextPath) — stopping poll timer")
            pollTimer?.invalidate()
            pollTimer = nil
            return
        }
        let playResult = manzo_play(nextHandle)
        NSLog("MANZO Phase 3: auto-advance to \(nextPath) — play result: \(playResult)")
    }

    // MARK: - Phase 4 UAT: temporary debug key handlers
    // Press 1–4 during playback to trigger the 4 UAT scenarios.
    // Remove this entire section (and the two call-sites below) after UAT is confirmed.

    private var uatKeyMonitor: Any?

    private func installUATKeyHandlers() {
        uatKeyMonitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { [weak self] event in
            guard let self else { return event }
            switch event.charactersIgnoringModifiers {
            case "1": self.uatEQBoostBands();  return nil
            case "2": self.uatPreampBoost();   return nil
            case "3": self.uatVolumeFade();    return nil
            case "4": self.uatPanSweep();      return nil
            default:  return event
            }
        }
        NSLog("MANZO UAT: key handlers active — 1=EQ boost, 2=preamp +12dB, 3=vol fade, 4=pan sweep")
    }

    private func removeUATKeyHandlers() {
        if let monitor = uatKeyMonitor {
            NSEvent.removeMonitor(monitor)
            uatKeyMonitor = nil
        }
    }

    /// UAT-1: boost bands 0 (70 Hz) and 9 (16 kHz) to +12 dB; all other bands at 0 dB.
    private func uatEQBoostBands() {
        guard let handle = manzoHandle else { NSLog("MANZO UAT-1: no handle"); return }
        var gains = [Float](repeating: 0, count: 10)
        gains[0] = 12.0
        gains[9] = 12.0
        gains.withUnsafeBufferPointer { manzo_set_eq(handle, $0.baseAddress!, 0.0) }
        NSLog("MANZO UAT-1: bands 0+9 → +12 dB (preamp 0 dB)")
    }

    /// UAT-2: set preamp to +12 dB; all bands at 0 dB.
    private func uatPreampBoost() {
        guard let handle = manzoHandle else { NSLog("MANZO UAT-2: no handle"); return }
        let gains = [Float](repeating: 0, count: 10)
        gains.withUnsafeBufferPointer { manzo_set_eq(handle, $0.baseAddress!, 12.0) }
        NSLog("MANZO UAT-2: preamp → +12 dB")
    }

    /// UAT-3: fade volume to 0 then restore to 1 after 500 ms.
    private func uatVolumeFade() {
        guard let handle = manzoHandle else { NSLog("MANZO UAT-3: no handle"); return }
        manzo_set_volume(handle, 0.0)
        NSLog("MANZO UAT-3: volume → 0.0, restoring in 500 ms")
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
            guard let h = self?.manzoHandle else { return }
            manzo_set_volume(h, 1.0)
            NSLog("MANZO UAT-3: volume → 1.0")
        }
    }

    /// UAT-4: pan sweep −1.0 → 0.0 → +1.0, 400 ms between steps.
    private func uatPanSweep() {
        guard let handle = manzoHandle else { NSLog("MANZO UAT-4: no handle"); return }
        manzo_set_pan(handle, -1.0)
        NSLog("MANZO UAT-4: pan → -1.0 (hard left)")
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.4) { [weak self] in
            guard let h = self?.manzoHandle else { return }
            manzo_set_pan(h, 0.0)
            NSLog("MANZO UAT-4: pan → 0.0 (center)")
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) { [weak self] in
            guard let h = self?.manzoHandle else { return }
            manzo_set_pan(h, 1.0)
            NSLog("MANZO UAT-4: pan → +1.0 (hard right)")
        }
    }

    // MARK: - Helpers

    /// Resolves a fixture path from the app bundle (Copy Bundle Resources).
    /// Falls back to MANZO_FIXTURE_DIR env var for CI overrides.
    /// Returns empty string if not found — caller checks fileExists.
    private func resolveFixturePath(name: String, ext: String) -> String {
        if let bundlePath = Bundle.main.path(forResource: name, ofType: ext) {
            return bundlePath
        }
        if let envDir = ProcessInfo.processInfo.environment["MANZO_FIXTURE_DIR"] {
            return (envDir as NSString).appendingPathComponent("\(name).\(ext)")
        }
        return ""
    }
}
