import AppKit

@objc class AppDelegate: NSObject, NSApplicationDelegate {
    // MARK: - State

    // Keep handle alive for the app's lifetime — stored as instance var prevents premature dealloc.
    // Type matches cbindgen output: struct manzo_ManzoHandle * → UnsafeMutablePointer<manzo_ManzoHandle>?
    private var manzoHandle: UnsafeMutablePointer<manzo_ManzoHandle>? = nil

    // Phase 3 (D-02): playback state constants — must match the i32 returned by manzo_get_state.
    // Defined here as Int32 locals (rather than C macros in the bridging header) to keep this
    // task self-contained; cbindgen emits the function but not symbolic state names.
    private let MANZO_STATE_PLAYING: Int32 = 1
    private let MANZO_STATE_PAUSED:  Int32 = 2
    private let MANZO_STATE_STOPPED: Int32 = 3
    private let MANZO_STATE_ENDED:   Int32 = 4

    // Phase 3 (D-05 / AUDIO-05): 2-track queue and polling timer for auto-advance demo.
    // The Swift main thread polls manzo_get_state every 100 ms; when ENDED is observed the
    // current handle is closed and the next track is opened + played. A silence gap during
    // the handoff is acceptable per D-05 (true gapless deferred to v2).
    private var trackQueue: [String] = []
    private var currentTrackIndex: Int = 0
    private var pollTimer: Timer? = nil

    // Phase 5: retain the window for the app's lifetime.
    // ARC would deallocate a window stored only in a local var on the next runloop cycle.
    private var manzoWindow: ManzoWindow? = nil

    // Phase 6: retained ManzoVisualStyle — loaded from UserDefaults in applicationDidFinishLaunching.
    // AppDelegate owns the current style per D-10.
    private var visualStyle: ManzoVisualStyle = .default

    // MARK: - NSApplicationDelegate

    func applicationDidFinishLaunching(_ notification: Notification) {
        // Build the main menu programmatically so Cmd-Q (and other standard key
        // equivalents) are wired up. Without a MainMenu.xib this is never done
        // automatically — NSApplication creates a bare menu with no key equivalents.
        buildMainMenu()

        // Phase 3: build the 2-track queue. Each entry resolves the path the same way Phase 2
        // resolved test.mp3 — bundle resource first, then dev fixture fallback. test2.mp3 is
        // generated by Plan 03-02; if absent, the queue still holds test.mp3 and the
        // auto-advance log will show "queue exhausted" cleanly.
        trackQueue = [
            resolveFixturePath(name: "test",  ext: "mp3"),
            resolveFixturePath(name: "test2", ext: "mp3"),
        ]

        // Open + play the first track (audio is optional — window always appears even if absent).
        let firstPath = trackQueue[currentTrackIndex]
        if !FileManager.default.fileExists(atPath: firstPath) {
            NSLog("MANZO Phase 3: first track not found at \(firstPath) — skipping playback")
        } else {
            manzoHandle = manzo_open(firstPath)
            if manzoHandle == nil {
                NSLog("MANZO Phase 3: manzo_open returned null for \(firstPath)")
            } else {
                let playResult = manzo_play(manzoHandle!)
                if playResult == 0 {
                    NSLog("MANZO Phase 3: playback started — \(firstPath)")
                } else {
                    NSLog("MANZO Phase 3: manzo_play failed with code \(playResult) — \(firstPath)")
                }

                // Phase 3 (D-05 / AUDIO-05): start 100 ms polling timer to detect ENDED and auto-advance.
                // Timer runs on the main runloop in default mode; pollPlaybackState reads state via FFI
                // and triggers the queue handoff when MANZO_STATE_ENDED is observed.
                pollTimer = Timer.scheduledTimer(
                    timeInterval: 0.1,
                    target: self,
                    selector: #selector(pollPlaybackState),
                    userInfo: nil,
                    repeats: true
                )
                NSLog("MANZO Phase 3: 100 ms state poll timer armed — queue size \(trackQueue.count)")
            }
        }

        // MARK: Phase 5 / Phase 6 — window setup + Neo-Aero style application
        // D-04 (Phase 5): isOpaque=false and backgroundColor=.clear set inside ManzoWindow.init()
        //                 before this call — already correct for compositor.
        // D-10 (Phase 6): ManzoVisualStyle loaded and applied before contentView assignment.
        let window   = ManzoWindow()
        let rootView = ManzoRootView(frame: window.frame)

        // Phase 6 (D-10): load persisted style (or default on first launch) and apply Neo-Aero chrome.
        visualStyle = ManzoVisualStyle.load()
        rootView.applyStyle(visualStyle)
        NSLog("MANZO Phase 6: ManzoVisualStyle loaded and applied — layout=%@, theme=%@, wetFloor=%d",
              visualStyle.panelLayout.rawValue, visualStyle.colorTheme.rawValue,
              visualStyle.wetFloor ? 1 : 0)

        window.contentView = rootView
        window.center()
        window.orderFront(nil)
        // D-12: single call — AppKit saves frame on move and restores on next launch automatically.
        // Must be called AFTER orderFront so AppKit can match the autosave name to the visible window.
        window.setFrameAutosaveName("ManzoMainWindow")
        manzoWindow = window   // retain: prevent ARC deallocation
        NSLog("MANZO Phase 5: window ordered front — 275×116 pt frameless, autosave=ManzoMainWindow")
    }

    func applicationWillTerminate(_ notification: Notification) {
        // Phase 3: stop the poll timer FIRST so it cannot fire after the handle is freed.
        pollTimer?.invalidate()
        pollTimer = nil

        // Release Rust handle on app exit — manzo_close drops the Arc and stops cpal stream (T-02-09).
        if let handle = manzoHandle {
            manzo_close(handle)
            manzoHandle = nil
        }
    }

    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        return true
    }

    // MARK: - Phase 3: auto-advance polling

    /// Polls the Rust core's playback state. When MANZO_STATE_ENDED is observed, advance to
    /// the next track in trackQueue (close current handle, open + play next). When the queue
    /// is exhausted, invalidate the timer cleanly.
    @objc private func pollPlaybackState() {
        guard let handle = manzoHandle else { return }

        let state = manzo_get_state(handle)
        guard state == MANZO_STATE_ENDED else { return }

        NSLog("MANZO Phase 3: track ended (state=4) — advancing queue")

        // Close the current handle BEFORE opening the next one to avoid two cpal streams alive
        // simultaneously (cpal default device only supports one output stream at a time on macOS).
        manzo_close(handle)
        manzoHandle = nil

        // Advance the queue cursor.
        currentTrackIndex += 1
        guard currentTrackIndex < trackQueue.count else {
            NSLog("MANZO Phase 3: queue exhausted (\(currentTrackIndex)/\(trackQueue.count)) — stopping poll timer")
            pollTimer?.invalidate()
            pollTimer = nil
            return
        }

        let nextPath = trackQueue[currentTrackIndex]
        guard FileManager.default.fileExists(atPath: nextPath) else {
            NSLog("MANZO Phase 3: next track not found at \(nextPath) — stopping poll timer")
            pollTimer?.invalidate()
            pollTimer = nil
            return
        }

        manzoHandle = manzo_open(nextPath)
        guard let nextHandle = manzoHandle else {
            NSLog("MANZO Phase 3: manzo_open returned null for next track \(nextPath) — stopping poll timer")
            pollTimer?.invalidate()
            pollTimer = nil
            return
        }
        let playResult = manzo_play(nextHandle)
        NSLog("MANZO Phase 3: auto-advance to \(nextPath) — play result: \(playResult)")
    }

    // MARK: - Menu

    /// Builds NSApp.mainMenu programmatically.
    ///
    /// This app has no MainMenu.xib (pure code-only UI). Without this call
    /// NSApplication synthesises a bare menu that renders visible items (Quit,
    /// Hide, etc.) via AppKit's automatic menu population, but the Quit item
    /// lacks a keyEquivalent — so Cmd-Q is never dispatched to terminate:.
    ///
    /// Structure mirrors the standard Xcode-generated MainMenu.xib:
    ///   [AppName]  →  About, —, Hide, Hide Others, Show All, —, Quit
    ///   [Window]   →  Minimize, Zoom, —, Bring All to Front
    ///
    /// Only the Application submenu is strictly required for Cmd-Q; the Window
    /// menu is included so AppKit window-management shortcuts (Cmd-M etc.) work.
    private func buildMainMenu() {
        let mainMenu = NSMenu()

        // ── Application menu ──────────────────────────────────────────────────
        let appMenuItem = NSMenuItem()
        mainMenu.addItem(appMenuItem)

        let appName = ProcessInfo.processInfo.processName
        let appMenu  = NSMenu()
        appMenuItem.submenu = appMenu

        appMenu.addItem(withTitle: "About \(appName)",
                        action: #selector(NSApplication.orderFrontStandardAboutPanel(_:)),
                        keyEquivalent: "")

        appMenu.addItem(.separator())

        appMenu.addItem(withTitle: "Hide \(appName)",
                        action: #selector(NSApplication.hide(_:)),
                        keyEquivalent: "h")

        let hideOthers = appMenu.addItem(withTitle: "Hide Others",
                                         action: #selector(NSApplication.hideOtherApplications(_:)),
                                         keyEquivalent: "h")
        hideOthers.keyEquivalentModifierMask = [.command, .option]

        appMenu.addItem(withTitle: "Show All",
                        action: #selector(NSApplication.unhideAllApplications(_:)),
                        keyEquivalent: "")

        appMenu.addItem(.separator())

        // Quit — this is the item that was missing its keyEquivalent.
        appMenu.addItem(withTitle: "Quit \(appName)",
                        action: #selector(NSApplication.terminate(_:)),
                        keyEquivalent: "q")

        // ── Window menu ───────────────────────────────────────────────────────
        let windowMenuItem = NSMenuItem()
        mainMenu.addItem(windowMenuItem)

        let windowMenu = NSMenu(title: "Window")
        windowMenuItem.submenu = windowMenu
        NSApp.windowsMenu = windowMenu

        windowMenu.addItem(withTitle: "Minimize",
                           action: #selector(NSWindow.miniaturize(_:)),
                           keyEquivalent: "m")

        windowMenu.addItem(withTitle: "Zoom",
                           action: #selector(NSWindow.zoom(_:)),
                           keyEquivalent: "")

        windowMenu.addItem(.separator())

        windowMenu.addItem(withTitle: "Bring All to Front",
                           action: #selector(NSApplication.arrangeInFront(_:)),
                           keyEquivalent: "")

        NSApp.mainMenu = mainMenu
        NSLog("MANZO: main menu built programmatically — Cmd-Q wired to terminate:")
    }

    // MARK: - Helpers

    /// Resolves a fixture path from the app bundle (Copy Bundle Resources).
    /// Falls back to MANZO_FIXTURE_DIR env var for CI overrides.
    /// Returns empty string if not found — caller checks fileExists.
    private func resolveFixturePath(name: String, ext: String) -> String {
        if let bundlePath = Bundle.main.path(forResource: name, ofType: ext) {
            return bundlePath
        }
        if let envDir = ProcessInfo.processInfo.environment["MANZO_FIXTURE_DIR"] {
            return (envDir as NSString).appendingPathComponent("\(name).\(ext)")
        }
        return ""
    }
}
